[package]
name = "rate-streamer"
version.workspace = true
edition.workspace = true

[dependencies]
common = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
rustls = { workspace = true }
axum = { workspace = true }
axum-client-ip = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
redis = { workspace = true }
uuid = { workspace = true }
