[package]
name = "admin-api"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
rustls = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
redis = { workspace = true }
uuid = { workspace = true }
sha2 = { workspace = true }
