[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
envconfig = "0.11.1"
redis = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
async-stream = { workspace = true }
futures-util = { workspace = true }
axum-client-ip = { workspace = true }
axum = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
