name: Build

on:
    push:
        branches-ignore:
            - master
    pull_request:
        branches:
            - master

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
    cancel-in-progress: true

env:
    CI: true
    CARGO_TERM_COLOR: always

jobs:
    Build:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  submodules: recursive
                  token: ${{ secrets.PAT_GITHUB_PUBLISH_ALL || github.token }}

            - name: Install Rust 1.96
              uses: dtolnay/rust-toolchain@1.96.0

            - name: Run tests
              run: cargo test --all --all-features

            - name: Build
              run: cargo build --all-features
